# Generated by Django 2.1.2 on 2021-03-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiariosGlobales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegacion_nr', models.IntegerField()),
                ('delegacion_name', models.CharField(max_length=350)),
                ('nombre_beneficiario', models.CharField(max_length=250)),
                ('documentacion_beneficiario', models.CharField(max_length=250)),
                ('ciudad', models.CharField(max_length=256)),
                ('provincia', models.CharField(max_length=256)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
