# Generated by Django 2.1.2 on 2021-02-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegacionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=400)),
                ('codigo_postal', models.IntegerField()),
                ('ciudad', models.CharField(max_length=255)),
                ('telegram_code', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='otros_documentos',
            field=models.CharField(default='', max_length=40, null=True),
        ),
    ]
