# Generated by Django 2.1.2 on 2021-02-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0004_auto_20210222_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegaciondata',
            name='telegram_code',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
