# Generated by Django 2.1.2 on 2021-02-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0005_auto_20210222_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='hijo',
            name='otros_documentos',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
