# Generated by Django 2.1.2 on 2021-02-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0006_hijo_otros_documentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegaciondata',
            name='provincia',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
