# Generated by Django 2.1.2 on 2021-02-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0008_delegaciondata_domain_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=400)),
                ('fecha', models.DateTimeField()),
                ('importe', models.IntegerField(default=0)),
            ],
        ),
    ]
