# Generated by Django 2.1.2 on 2021-02-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0009_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(choices=[(1, 'Ingreso'), (2, 'Gasto')], default='', max_length=50),
        ),
    ]
